version: '3'
services:
  web:
    restart: always
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
  php:
    image: php:fpm
    volumes:
      - ./app:/app
    links:
      - db
  db:
    image: mysql:latest
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=training_nfq
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3306
    volumes:
      - ./dbdata:/var/lib/mysql

  phpmyadmin:
    container_name: phpMyAdmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "9080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - PMA_HOST=db